language: node_js
node_js:
  - 'node'
cache:
  yarn: true
  directories:
    - node_modules
script:
  - npm run validate
  - npm run build
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: build
    keep_history: true
    on:
      branch: $BRANCH_NAME
notifications:
  email:
    - chhabradolly93@gmail.com
