language: node_js
node_js:
  - "10"
cache:
  npm: true
  yarn: true
  directories:
    - node_modules
script:
  - yarn test
  - yarn test --coverage
  - yarn build
  - npm run test
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: build
    keep_history: true
    on:
      branch: $BRANCH_NAME
notifications:
  email:
    - chhabradolly93@gmail.com
