export const FETCH_HOME_PAGE_DATA =
  'HACKER_NEWS_APP/HOME_PAGE/FETCH_HOME_PAGE_DATA';
export const FETCH_HOME_PAGE_DATA_SUCCESS =
  'HACKER_NEWS_APP/HOME_PAGE/FETCH_HOME_PAGE_DATA_SUCCESS';
export const FETCH_HOME_PAGE_DATA_ERROR =
  'HACKER_NEWS_APP/HOME_PAGE/FETCH_HOME_PAGE_DATA_ERROR';
