export const FETCH_HOME_PAGE_DATA =
  'HACKER_NEWS_APP/HOME_PAGE/FETCH_HOME_PAGE_DATA';
export const FETCH_HOME_PAGE_DATA_SUCCESS =
  'HACKER_NEWS_APP/HOME_PAGE/FETCH_HOME_PAGE_DATA_SUCCESS';
export const FETCH_HOME_PAGE_DATA_ERROR =
  'HACKER_NEWS_APP/HOME_PAGE/FETCH_HOME_PAGE_DATA_ERROR';
export const HIDE_DATA_KEY = 'HACKER_NEWS_APP/HOME_PAGE/HIDE_DATA_KEY';
export const HIDE_DATA = 'HACKER_NEWS_APP/HOME_PAGE/HIDE_DATA';
