const homePageData = {
  hits: [
    {
      created_at: '2018-03-14T03:50:30.000Z',
      title: 'Stephen Hawking has died',
      url: 'http://www.bbc.com/news/uk-43396008',
      author: 'Cogito',
      points: 6015,
      story_text: null,
      comment_text: null,
      num_comments: 436,
      story_id: null,
      story_title: null,
      story_url: null,
      parent_id: null,
      created_at_i: 1520999430,
      relevancy_score: 8012,
      _tags: ['story', 'author_Cogito', 'story_16582136'],
      objectID: '16582136',
      _highlightResult: {
        title: {
          value: 'Stephen Hawking has died',
          matchLevel: 'none',
          matchedWords: [],
        },
        url: {
          value: 'http://www.bbc.com/news/uk-43396008',
          matchLevel: 'none',
          matchedWords: [],
        },
        author: {
          value: 'Cogito',
          matchLevel: 'none',
          matchedWords: [],
        },
      },
    },
    {
      created_at: '2016-02-17T08:38:37.000Z',
      title: 'A Message to Our Customers',
      url: 'http://www.apple.com/customer-letter/',
      author: 'epaga',
      points: 5771,
      story_text: null,
      comment_text: null,
      num_comments: 967,
      story_id: null,
      story_title: null,
      story_url: null,
      parent_id: null,
      created_at_i: 1455698317,
      relevancy_score: 6561,
      _tags: ['story', 'author_epaga', 'story_11116274'],
      objectID: '11116274',
      _highlightResult: {
        title: {
          value: 'A Message to Our Customers',
          matchLevel: 'none',
          matchedWords: [],
        },
        url: {
          value: 'http://www.apple.com/customer-letter/',
          matchLevel: 'none',
          matchedWords: [],
        },
        author: {
          value: 'epaga',
          matchLevel: 'none',
          matchedWords: [],
        },
      },
    },
    {
      created_at: '2011-10-05T23:42:23.000Z',
      title: 'Steve Jobs has passed away.',
      url: 'http://www.apple.com/stevejobs/',
      author: 'patricktomas',
      points: 4271,
      story_text: '',
      comment_text: null,
      num_comments: 376,
      story_id: null,
      story_title: null,
      story_url: null,
      parent_id: null,
      created_at_i: 1317858143,
      relevancy_score: 3496,
      _tags: ['story', 'author_patricktomas', 'story_3078128'],
      objectID: '3078128',
      _highlightResult: {
        title: {
          value: 'Steve Jobs has passed away.',
          matchLevel: 'none',
          matchedWords: [],
        },
        url: {
          value: 'http://www.apple.com/stevejobs/',
          matchLevel: 'none',
          matchedWords: [],
        },
        author: {
          value: 'patricktomas',
          matchLevel: 'none',
          matchedWords: [],
        },
        story_text: {
          value: '',
          matchLevel: 'none',
          matchedWords: [],
        },
      },
    },
  ],
  nbHits: 22,
  page: 1,
  nbPages: 2,
  hitsPerPage: 20,
  exhaustiveNbHits: true,
  query: '',
  params:
    'advancedSyntax=true&analytics=true&analyticsTags=backend&page=1&tags=front_page',
  processingTimeMS: 1,
};

export default homePageData;
